# Generated by Django 4.1.3 on 2022-11-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.TextField()),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.IntegerField()),
            ],
        ),
    ]
